import type {Metadata} from "next";

import "../globals.css";
import {Toaster} from "@/components/ui/toaster";
import {AppSidebar} from "@/components/app-sidebar";
import {SidebarProvider} from "@/components/ui/sidebar";

export const metadata: Metadata = {
  title: "life-sphere-app",
  description: "Generated by appncy",
};

export default async function RootLayout({children}: {children: React.ReactNode}) {
  return (
    <html lang="en">
      <body className="">
        <SidebarProvider>
          <AppSidebar />
          {children}
        </SidebarProvider>
        <Toaster />
      </body>
    </html>
  );
}
