import type {Metadata} from "next";

import "../../globals.css";
import {Toaster} from "@/components/ui/toaster";

export const metadata: Metadata = {
  title: "life-sphere-app",
  description: "Generated by appncy",
};

export default async function RootLayout({children}: {children: React.ReactNode}) {
  return (
    <html lang="en">
      <body className="">
        {/* <body className="grid min-h-screen grid-rows-[auto,1fr,auto] gap-8 bg-background px-4 font-sans antialiased"> */}
        {children}
        <Toaster />
      </body>
    </html>
  );
}
